#!/bin/bash
#--------------------------------------------------------------
#
#SBATCH --job-name=allAff_age_clustSim
#SBATCH --output=output/allAff_age_clustSim.log
#SBATCH --error=output/allAff_age_clustSim_error.log
#SBATCH --cpus-per-task=25
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=4000
#SBATCH --partition=fat,short

# This script runs 3dClustSim for each model using acf parameters generated by calculateACF.sh

module unload intel
module load gcc/6.4 
module load afni

# Specify variables
# ------------------------------------------------------------------------------------------

# RX directories (where model masks can be found)
afniDir=/projects/dsnlab/shared/SFIC_Faces3/fMRI/analysis/rx/AFNI_masked/allAff

# Output directory to store thresholding info
outputDir=/projects/dsnlab/shared/SFIC_Faces3/fMRI/analysis/rx/AFNI_masked/thresholding/allAff

# Run 3dClustSim
# ------------------------------------------------------------------------------------------

#3dClustSim -mask "${afniDir}"/age/allAff_age+tlrc[0] -acf 0.487101  4.79048  12.0862 > "${outputDir}"/age.txt

#3dClustSim -mask "${afniDir}"/age_sq/allAff_age_sq+tlrc[0] -acf 0.486456  4.7948  12.023 > "${outputDir}"/age_sq.txt

#3dClustSim -mask "${afniDir}"/test_cub/allAff_test_cub+tlrc[0] -acf 0.479829  4.77772  11.9654 > "${outputDir}"/test_cub.txt

3dClustSim -mask "${afniDir}"/age_cubF/allAff_age_cub+tlrc[0] -acf 0.506756  4.8032  12.0368 > "${outputDir}"/age_cubF.txt

3dClustSim -mask "${afniDir}"/age_cubM/allAff_age_cub+tlrc[0] -acf 0.505008  4.70351  12.6229 > "${outputDir}"/age_cubM.txt

3dClustSim -mask "${afniDir}"/pds_cubF/allAff_pds_cub+tlrc[0] -acf 0.489163  4.81523  11.8407 > "${outputDir}"/pds_cubF.txt

3dClustSim -mask "${afniDir}"/pds_cubM/allAff_pds_cub+tlrc[0] -acf 0.484698  4.73242  12.2499 > "${outputDir}"/pds_cubM.txt

3dClustSim -mask "${afniDir}"/test_cubF/allAff_test_cub+tlrc[0] -acf 0.499564  4.76661  12.0728 > "${outputDir}"/test_cubF.txt

3dClustSim -mask "${afniDir}"/test_cubM/allAff_test_cub+tlrc[0] -acf 0.501671  4.70665  12.4056 > "${outputDir}"/test_cubM.txt
