#!/bin/bash

# This script runs 3dClustSim for each model using acf parameters generated by calculateACF.sh

module load prl afni

# Specify variables
# ------------------------------------------------------------------------------------------

# RX directories (where model masks can be found)
afniDir=/projects/dsnlab/SFIC_Faces3/fMRI/analysis/rx/AFNI

# Output directory to store thresholding info
outputDir=/projects/dsnlab/SFIC_Faces3/fMRI/analysis/rx/AFNI/thresholding

# Run 3dClustSim
# ------------------------------------------------------------------------------------------

3dClustSim -mask "${afniDir}"/allAff_pds/allAff_pds+tlrc[0] -acf 0.517748  5.00012  12.0729 > "${outputDir}"/allAff_pds.txt

3dClustSim -mask "${afniDir}"/allAff_pds/allAff_pds_age+tlrc[0] -acf 0.519856  4.99611  12.109 > "${outputDir}"/allAff_pds_age.txt

3dClustSim -mask "${afniDir}"/allAff_logtest/allAff_logtest+tlrc[0] -acf 0.511793  5.01331  11.9206 > "${outputDir}"/allAff_logtest.txt

3dClustSim -mask "${afniDir}"/allAff_logtest/allAff_logtest_age+tlrc[0] -acf 0.511296  5.01407  11.9241 > "${outputDir}"/allAff_logtest_age.txt

3dClustSim -mask "${afniDir}"/eachAff_pds/eachAff_pds+tlrc[0] -acf 0.516609  4.89175  12.0033 > "${outputDir}"/eachAff_pds.txt

3dClustSim -mask "${afniDir}"/eachAff_pds/eachAff_pds_age+tlrc[0] -acf 0.518327  4.893  12.0326 > "${outputDir}"/eachAff_pds_age.txt

3dClustSim -mask "${afniDir}"/eachAff_logtest/eachAff_logtest+tlrc[0] -acf 0.513394  4.88828  11.9694 > "${outputDir}"/eachAff_logtest.txt

3dClustSim -mask "${afniDir}"/eachAff_logtest/eachAff_logtest_age+tlrc[0] -acf 0.51372  4.88934  11.9803 > "${outputDir}"/eachAff_logtest_age.txt

#3dClustSim -mask "${afniDir}"/allAff_age/allAff_age+tlrc[0] -acf 0.513196  5.01536  11.8679 > "${outputDir}"/allAff_age.txt

#3dClustSim -mask "${afniDir}"/allAff_pds_female/allAff_pds_female+tlrc[0] -acf 0.498853  5.03195  11.616 > "${outputDir}"/allAff_pds_female.txt

#3dClustSim -mask "${afniDir}"/allAff_pds_male/allAff_pds_male+tlrc[0] -acf 0.489787  4.99616  11.8327 > "${outputDir}"/allAff_pds_male.txt

#3dClustSim -mask "${afniDir}"/allAff_logtest_female/allAff_logtest_female+tlrc[0] -acf 0.495818  5.00338  11.3704 > "${outputDir}"/allAff_logtest_female.txt

#3dClustSim -mask "${afniDir}"/allAff_logtest_male/allAff_logtest_male+tlrc[0] -acf 0.491569  5.00337  11.9905 > "${outputDir}"/allAff_logtest_male.txt

#3dClustSim -mask "${afniDir}"/allAff_pds_female/allAff_pds_age_female+tlrc[0] -acf 0.501473  5.02738  11.6646 > "${outputDir}"/allAff_pds_age_female.txt

#3dClustSim -mask "${afniDir}"/allAff_pds_male/allAff_pds_age_male+tlrc[0] -acf 0.49286  4.99204  11.8418 > "${outputDir}"/allAff_pds_age_male.txt

#3dClustSim -mask "${afniDir}"/allAff_logtest_female/allAff_logtest_age_female+tlrc[0] -acf 0.498813  4.99919  11.4282 > "${outputDir}"/allAff_logtest_age_female.txt

#3dClustSim -mask "${afniDir}"/allAff_logtest_male/allAff_logtest_age_male+tlrc[0] -acf 0.489427  5.00685  11.9074 > "${outputDir}"/allAff_logtest_age_male.txt

#3dClustSim -mask "${afniDir}"/eachAff_age/eachAff_age+tlrc[0] -acf 0.516664  4.89457  11.9309 > "${outputDir}"/eachAff_age.txt

#3dClustSim -mask "${afniDir}"/eachAff_pds_female/eachAff_pds_female+tlrc[0] -acf 0.513363  4.91403  11.805 > "${outputDir}"/eachAff_pds_female.txt

#3dClustSim -mask "${afniDir}"/eachAff_pds_male/eachAff_pds_male+tlrc[0] -acf 0.514121  4.84841  12.1415 > "${outputDir}"/eachAff_pds_male.txt

#3dClustSim -mask "${afniDir}"/eachAff_logtest_female/eachAff_logtest_female+tlrc[0] -acf 0.510319  4.90094  11.7162 > "${outputDir}"/eachAff_logtest_female.txt

#3dClustSim -mask "${afniDir}"/eachAff_logtest_male/eachAff_logtest_male+tlrc[0] -acf 0.510974  4.84949  12.1699 > "${outputDir}"/eachAff_logtest_male.txt

#3dClustSim -mask "${afniDir}"/eachAff_pds_female/eachAff_pds_age_female+tlrc[0] -acf 0.519991  4.92127  11.874 > "${outputDir}"/eachAff_pds_age_female.txt

#3dClustSim -mask "${afniDir}"/eachAff_pds_male/eachAff_pds_age_male+tlrc[0] -acf 0.517566  4.85133  12.1837 > "${outputDir}"/eachAff_pds_age_male.txt

#3dClustSim -mask "${afniDir}"/eachAff_logtest_female/eachAff_logtest_age_female+tlrc[0] -acf 0.512457  4.90314  11.7582 > "${outputDir}"/eachAff_logtest_age_female.txt

#3dClustSim -mask "${afniDir}"/eachAff_logtest_male/eachAff_logtest_age_male+tlrc[0] -acf 0.511909  4.85482  12.1706 > "${outputDir}"/eachAff_logtest_age_male.txt
