---
title: "Make 3dLME data table"
author: "Nandi Vijayakumar"
output: html_document
---

This script takes first-level FX contrasts (each condition > rest) and age/puberty covariates to create the data table input for the 3dLME model.

## load packages
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
```

## load data
```{r}
#set directory
setwd('/Volumes/psych-cog/dsnlab/SFIC/nonbids_data/fMRI/analysis/rx/AFNI/FX_models')

# load csv file with fx con file names
#fxCons = data.frame(file = list.files('./data/FX_models/')) # get file names from contrast .nii files
fxCons = read.csv('fxCons.csv',header=F)
fxCons <- setNames(fxCons, "file")
  
# print header
fxCons %>%
  head(6) %>%
  kable(format = 'pandoc')

# extract condition information from contrast files
fxCons_allAff = fxCons %>%
  filter(grepl("con_0006", file)) %>%
  extract(file, c("subid","wave","con"), 
          regex = "sub-L0([0-9]{2})_ses-wave([1-3]{1})_(con_[0-6]{4}).nii", 
          remove = FALSE) %>%
  mutate(InputFile = paste0('/Volumes/psych-cog/dsnlab/SFIC/nonbids_data/fMRI/analysis/rx/AFNI/FX_models/',file), # CHANGE THIS PATH
         subid = as.integer(subid),
         wave = as.factor(wave))

fxCons_eachAff = fxCons %>%
  extract(file, c("subid","wave","con"), 
          regex = "sub-L0([0-9]{2})_ses-wave([1-3]{1})_(con_[0-5]{4}).nii", 
          remove = FALSE) %>%
  mutate(affect = ifelse(con %in% "con_0001", "angry",
                         ifelse(con %in% "con_0002", "fear",
                               ifelse(con %in% "con_0003", "sad",
                                      ifelse(con %in% "con_0004", "happy",
                                             ifelse(con %in% "con_0005", "neutral", NA))))),
         InputFile = paste0('/Volumes/psych-cog/dsnlab/SFIC/nonbids_data/fMRI/analysis/rx/AFNI/FX_models/',file), # CHANGE THIS PATH
         wave = as.factor(wave))
```

## create age files
```{r}
# load age
age_covariate = read.csv("/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/age.csv")

# print header
age_covariate %>%
  head(6) %>%
  kable(format = 'pandoc')

# center age and create quadratic term for age
age_covariate = age_covariate %>%
  mutate(age_c = age-(mean(age)),
         age_c2 = age_c^2,
         subid = as.integer(subid),
         wave = as.factor(wave)) %>%
  select(subid, wave, gender, starts_with("age_c"))

age_allAff = left_join(age_covariate, fxCons_allAff, by = c("subid", "wave")) %>%
  mutate(Subj = subid) %>%
  select(Subj, gender, starts_with("age_c"), InputFile) %>%
  mutate(Subj = sprintf("%02d", Subj)) %>%
  arrange(Subj)

age_allAff %>%
  head(10) %>%
  kable(format = 'pandoc')

write.table(age_allAff, '/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/age_allAff.txt', sep = "\t", quote=FALSE, row.names = FALSE)
```

## create pds files
```{r}
# load age
pds_covariate = read.csv("/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/pds.csv")

pds_covariate_female <- pds_covariate %>%
  filter(gender == "female")

pds_covariate_male <- pds_covariate %>%
  filter(gender == "male")

# print header
pds_covariate %>%
  head(6) %>%
  kable(format = 'pandoc')

# center age and create quadratic term for age
pds_covariate = pds_covariate %>%
  mutate(pdss_c = pdss-(mean(pdss)),
         pdss_c2 = pdss_c^2,
         age_c = age-(mean(age)),
         age_c2 = age_c^2,
         subid = as.integer(subid),
         wave = as.factor(wave)) %>%
  select(subid, wave, gender, contains("_c"))

pds_allAff = left_join(pds_covariate, fxCons_allAff, by = c("subid", "wave")) %>%
  mutate(Subj = subid) %>%
  select(Subj, gender, contains("_c"), InputFile) %>%
  mutate(Subj = sprintf("%02d", Subj)) %>%
  arrange(Subj)
  
pds_allAff %>%
  head(10) %>%
  kable(format = 'pandoc')

write.table(pds_allAff, '/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/pds_allAff.txt', sep = "\t", quote=FALSE, row.names = FALSE)

# create as above for females
pds_covariate_female = pds_covariate_female %>%
  mutate(pdss_c = pdss-(mean(pdss)),
         pdss_c2 = pdss_c^2,
         age_c = age-(mean(age)),
         age_c2 = age_c^2,
         subid = as.integer(subid),
         wave = as.factor(wave)) %>%
  select(subid, wave, gender, contains("_c"))

pds_allAff_female = left_join(pds_covariate_female, fxCons_allAff, by = c("subid", "wave")) %>%
  mutate(Subj = subid) %>%
  select(Subj, gender, contains("_c"), InputFile) %>%
  mutate(Subj = sprintf("%02d", Subj)) %>%
  arrange(Subj)
  
pds_allAff_female %>%
  head(10) %>%
  kable(format = 'pandoc')

write.table(pds_allAff_female, '/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/pds_allAff_female.txt', sep = "\t", quote=FALSE, row.names = FALSE)

# create as above for males
pds_covariate_male = pds_covariate_male %>%
  mutate(pdss_c = pdss-(mean(pdss)),
         pdss_c2 = pdss_c^2,
         age_c = age-(mean(age)),
         age_c2 = age_c^2,
         subid = as.integer(subid),
         wave = as.factor(wave)) %>%
  select(subid, wave, gender, contains("_c"))

pds_allAff_male = left_join(pds_covariate_male, fxCons_allAff, by = c("subid", "wave")) %>%
  mutate(Subj = subid) %>%
  select(Subj, gender, contains("_c"), InputFile) %>%
  mutate(Subj = sprintf("%02d", Subj)) %>%
  arrange(Subj)
  
pds_allAff_male %>%
  head(10) %>%
  kable(format = 'pandoc')

write.table(pds_allAff_male, '/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/pds_allAff_male.txt', sep = "\t", quote=FALSE, row.names = FALSE)
```

## create testosterone files
```{r}
# load age
test_covariate = read.csv("/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/testosterone.csv")

test_covariate_female <- test_covariate %>%
  filter(gender == "female")

test_covariate_male <- test_covariate %>%
  filter(gender == "male")

# print header
test_covariate %>%
  head(6) %>%
  kable(format = 'pandoc')

# center age and create quadratic term for age
test_covariate = test_covariate %>%
  mutate(test_c = testMean-(mean(testMean)),
         test_c2 = test_c^2,
         age_c = age-(mean(age)),
         age_c2 = age_c^2,
         subid = as.integer(subid),
         wave = as.factor(wave)) %>%
  select(subid, wave, gender, contains("_c"))

test_allAff = left_join(test_covariate, fxCons_allAff, by = c("subid", "wave")) %>%
  mutate(Subj = subid) %>%
  select(Subj, gender, contains("age_c"), InputFile) %>%
  mutate(Subj = sprintf("%02d", Subj)) %>%
  arrange(Subj)
  
test_allAff %>%
  head(10) %>%
  kable(format = 'pandoc')

write.table(test_allAff, '/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/testosterone_allAff.txt', sep = "\t", quote=FALSE, row.names = FALSE)

# create as above for females
test_covariate_female = test_covariate_female %>%
  mutate(test_c = testMean-(mean(testMean)),
         test_c2 = test_c^2,
         age_c = age-(mean(age)),
         age_c2 = age_c^2,
         subid = as.integer(subid),
         wave = as.factor(wave)) %>%
  select(subid, wave, gender, contains("_c"))

test_allAff_female = left_join(test_covariate_female, fxCons_allAff, by = c("subid", "wave")) %>%
  mutate(Subj = subid) %>%
  select(Subj, gender, contains("_c"), InputFile) %>%
  mutate(Subj = sprintf("%02d", Subj)) %>%
  arrange(Subj)
  
test_allAff_female %>%
  head(10) %>%
  kable(format = 'pandoc')

write.table(test_allAff_female, '/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/testosterone_allAff_female.txt', sep = "\t", quote=FALSE, row.names = FALSE)

# create as above for males
test_covariate_male = test_covariate_male %>%
  mutate(test_c = testMean-(mean(testMean)),
         test_c2 = test_c^2,
         age_c = age-(mean(age)),
         age_c2 = age_c^2,
         subid = as.integer(subid),
         wave = as.factor(wave)) %>%
  select(subid, wave, gender, contains("_c"))

test_allAff_male = left_join(test_covariate_male, fxCons_allAff, by = c("subid", "wave")) %>%
  mutate(Subj = subid) %>%
  select(Subj, gender, contains("_c"), InputFile) %>%
  mutate(Subj = sprintf("%02d", Subj)) %>%
  arrange(Subj)
  
test_allAff_male %>%
  head(10) %>%
  kable(format = 'pandoc')

write.table(test_allAff_male, '/Volumes/psych-cog/dsnlab/SFIC/SFIC_faces3_scripts/fMRI/rx/3dLME/testosterone_allAff_male.txt', sep = "\t", quote=FALSE, row.names = FALSE)
```